version: '3.8'

x-cache-from:
  - &app-cache-from
    cache_from:
      - php:8.0-fpm


services:
###> doctrine/doctrine-bundle ###
  db:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  php:
      image: php:8.0-fpm
      build:
        context: ./docker/php-fpm
        <<: *app-cache-from
      depends_on:
        - db
      environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
      healthcheck:
        interval: 10s
        timeout: 3s
        retries: 3
        start_period: 30s
      volumes:
        - ./:/var/www
        - app-cache:/var/www/var

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
  app-cache: {}
###< doctrine/doctrine-bundle ###
